"use client";

import { useMemo, useState } from "react";
import { documents } from "@/lib/mock-data";
import { formatDate } from "@/lib/date";
import { Button } from "@/components/ui/Button";
import { EmptyState } from "@/components/ui/EmptyState";

export function DocumentsView() {
  const [query,setQuery]=useState("");
  const [category,setCategory]=useState("Alle categorieën");
  const filtered=useMemo(()=>documents.filter(doc=>doc.name.toLowerCase().includes(query.toLowerCase())&&(category==="Alle categorieën"||doc.category===category)),[query,category]);
  return <div className="p-4 sm:p-6 lg:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Projectdossier</p><h2 className="mt-2 text-2xl font-black">Documenten</h2><p className="mt-2 text-sm text-[#68727a]">Bestanden per project en activiteit. Alle bestanden hieronder zijn mockdata.</p></div><Button onClick={()=>alert("Uploaden is in deze eerste demo niet gekoppeld aan opslag.")}>↑ Bestand uploaden</Button></div><div className="mt-6 surface p-4"><div className="grid gap-3 sm:grid-cols-[1fr_220px_auto]"><input className="min-h-11 rounded-xl border border-[#d4d9dc] px-3 text-sm" placeholder="Zoek op bestandsnaam" value={query} onChange={e=>setQuery(e.target.value)}/><select className="min-h-11 rounded-xl border border-[#d4d9dc] bg-white px-3 text-sm font-bold" value={category} onChange={e=>setCategory(e.target.value)}><option>Alle categorieën</option>{Array.from(new Set(documents.map(d=>d.category))).map(item=><option key={item}>{item}</option>)}</select><Button variant="ghost" onClick={()=>{setQuery("");setCategory("Alle categorieën");}}>Wissen</Button></div></div><div className="mt-6 surface overflow-hidden">{filtered.length?<div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-[#f4f5f3] text-[10px] uppercase tracking-[.08em] text-[#707a80]"><tr><th className="p-4">Bestand</th><th className="p-4">Categorie</th><th className="p-4">Versie</th><th className="p-4">Bijgewerkt</th><th className="p-4">Eigenaar</th><th className="p-4">Grootte</th><th className="p-4"></th></tr></thead><tbody>{filtered.map(doc=><tr key={doc.id} className="border-t border-[#e0e3e4]"><td className="p-4"><strong>{doc.name}</strong><p className="mt-1 text-xs text-[#7a848a]">{doc.activityId?"Gekoppeld aan activiteit":"Projectbreed document"}</p></td><td className="p-4 font-bold">{doc.category}</td><td className="p-4">{doc.version}</td><td className="p-4">{formatDate(doc.updatedAt)}</td><td className="p-4">{doc.owner}</td><td className="p-4">{doc.size}</td><td className="p-4"><div className="flex gap-2"><button className="rounded-lg border border-[#d5dade] px-3 py-2 text-xs font-extrabold" onClick={()=>alert(`${doc.name} wordt als mockbestand geopend.`)}>Open</button><button className="rounded-lg bg-[#1d2226] px-3 py-2 text-xs font-extrabold text-white" onClick={()=>alert("Download is uitgeschakeld omdat dit fictieve mockdata is.")}>Download</button></div></td></tr>)}</tbody></table></div>:<div className="p-5"><EmptyState title="Geen documenten gevonden" description="Pas de zoekterm of categorie aan."/></div>}</div></div>;
}
