import type { Activity, BuildingPart, Issue, Project, ProjectDocument, TeamMember } from "./types";

export const projects: Project[] = [
  {
    id: "havenkwartier",
    name: "Nieuwbouw appartementencomplex Havenkwartier",
    location: "Rotterdam",
    client: "Havenstede Ontwikkeling B.V.",
    contractor: "Van Dijk Bouwgroep",
    startDate: "2026-02-02",
    endDate: "2027-03-19",
    progress: 37,
    plannedProgress: 41,
    status: "Aandacht nodig",
    openIssues: 4,
    nextMilestone: "Gebouw wind- en waterdicht",
    nextMilestoneDate: "2026-09-18",
    type: "Woningbouw",
  },
  {
    id: "utrecht-kantoor",
    name: "Renovatie kantoorgebouw Utrecht",
    location: "Utrecht",
    client: "Merwede Vastgoed",
    contractor: "Kernbouw Renovatie",
    startDate: "2026-04-13",
    endDate: "2026-12-18",
    progress: 52,
    plannedProgress: 50,
    status: "Op schema",
    openIssues: 1,
    nextMilestone: "Start afbouw verdieping 4",
    nextMilestoneDate: "2026-08-17",
    type: "Renovatie",
  },
  {
    id: "dc-nijmegen",
    name: "Nieuwbouw distributiecentrum Nijmegen",
    location: "Nijmegen",
    client: "Waal Logistics Properties",
    contractor: "Bouwcombinatie Oost",
    startDate: "2026-01-12",
    endDate: "2026-11-27",
    progress: 63,
    plannedProgress: 69,
    status: "Vertraagd",
    openIssues: 7,
    nextMilestone: "Inbedrijfstelling sprinklerinstallatie",
    nextMilestoneDate: "2026-08-28",
    type: "Logistiek",
  },
  {
    id: "school-eindhoven",
    name: "Uitbreiding Campus De Groene Zoom",
    location: "Eindhoven",
    client: "Stichting Onderwijs Zuid",
    contractor: "Brabant Bouwpartners",
    startDate: "2026-06-01",
    endDate: "2027-01-29",
    progress: 18,
    plannedProgress: 19,
    status: "Op schema",
    openIssues: 2,
    nextMilestone: "Storten beganegrondvloer",
    nextMilestoneDate: "2026-08-11",
    type: "Onderwijs",
  },
];

export const activities: Activity[] = [
  {
    id: "grondwerk",
    name: "Grondwerk en bouwrijp maken",
    phase: "Terrein",
    startDate: "2026-02-02",
    endDate: "2026-02-20",
    responsible: "De Waal Grondwerken",
    status: "Gereed",
    progress: 100,
    dependencies: [],
    description: "Ontgraven bouwput, grondverbetering, drainage en tijdelijke bouwwegen.",
    attachments: [{ name: "Werkplan grondwerk v3.pdf", type: "PDF" }],
    issueIds: [],
    modelPartIds: ["terrain"],
  },
  {
    id: "fundering",
    name: "Paalfundering en funderingsbalken",
    phase: "Fundering",
    startDate: "2026-02-16",
    endDate: "2026-03-20",
    responsible: "Fundex Nederland",
    status: "Gereed",
    progress: 100,
    dependencies: ["grondwerk"],
    description: "Aanbrengen prefab heipalen, poeren, funderingsbalken en liftputten.",
    attachments: [
      { name: "Funderingsplan C-201.pdf", type: "PDF" },
      { name: "Heirapport week 9.xlsx", type: "XLSX" },
    ],
    issueIds: [],
    modelPartIds: ["foundation-a", "foundation-b"],
  },
  {
    id: "beganegrondvloer",
    name: "Beganegrondvloer",
    phase: "Ruwbouw",
    startDate: "2026-03-16",
    endDate: "2026-04-10",
    responsible: "Betonbouw Rijnmond",
    status: "Gereed",
    progress: 100,
    dependencies: ["fundering"],
    description: "Kanaalplaatvloer, druklaag en sparingen voor hoofdtracés.",
    attachments: [{ name: "Legplan kanaalplaten BG.pdf", type: "PDF" }],
    issueIds: [],
    modelPartIds: ["ground-floor"],
  },
  {
    id: "staalconstructie",
    name: "Hoofddraagconstructie",
    phase: "Ruwbouw",
    startDate: "2026-04-06",
    endDate: "2026-06-12",
    responsible: "Metaalbouw De Groot",
    status: "Vertraagd",
    progress: 88,
    dependencies: ["beganegrondvloer"],
    description: "Montage kolommen, liggers, stabiliteitsverbanden en bordessen.",
    attachments: [
      { name: "Montagevolgorde staal v5.pdf", type: "PDF" },
      { name: "Modelcontrole clashrapport.bcf", type: "BCF" },
    ],
    issueIds: ["issue-steel"],
    modelPartIds: ["frame-left", "frame-right", "floor-1", "floor-2"],
  },
  {
    id: "gevelsluiting",
    name: "Gevelsluiting en kozijnen",
    phase: "Gevel & dak",
    startDate: "2026-06-01",
    endDate: "2026-09-11",
    responsible: "Façade Partners B.V.",
    status: "In uitvoering",
    progress: 42,
    dependencies: ["staalconstructie"],
    description: "Houtskelet gevelelementen, aluminium kozijnen, glas en gevelbekleding.",
    attachments: [
      { name: "Gevelengineering statuslijst.pdf", type: "PDF" },
      { name: "Kozijnstaat blok A.xlsx", type: "XLSX" },
    ],
    issueIds: ["issue-windows"],
    modelPartIds: ["facade-front", "facade-back", "facade-left", "facade-right"],
  },
  {
    id: "dakwerk",
    name: "Dakconstructie en dakbedekking",
    phase: "Gevel & dak",
    startDate: "2026-07-06",
    endDate: "2026-08-28",
    responsible: "Dakteam Holland",
    status: "In uitvoering",
    progress: 35,
    dependencies: ["staalconstructie"],
    description: "Dakplaten, isolatie, bitumineuze dakbedekking, opstanden en hemelwaterafvoer.",
    attachments: [{ name: "Dakdetails D-410.pdf", type: "PDF" }],
    issueIds: [],
    modelPartIds: ["roof"],
  },
  {
    id: "binnenwanden",
    name: "Binnenwanden en schachten",
    phase: "Afbouw",
    startDate: "2026-08-03",
    endDate: "2026-11-20",
    responsible: "Interbouw Afbouw",
    status: "Gepland",
    progress: 0,
    dependencies: ["gevelsluiting"],
    description: "Metal-studwanden, woningscheidende wanden en brandwerende schachten.",
    attachments: [{ name: "Wandtypenboek.pdf", type: "PDF" }],
    issueIds: ["issue-drawing"],
    modelPartIds: ["walls-inner"],
  },
  {
    id: "installaties",
    name: "Ruwbouwinstallaties",
    phase: "Installaties",
    startDate: "2026-07-20",
    endDate: "2026-12-18",
    responsible: "Techniekcombinatie Delta",
    status: "In uitvoering",
    progress: 12,
    dependencies: ["staalconstructie"],
    description: "Hoofdtracés E/W, stijgleidingen, ventilatiekanalen en sprinklerleidingen.",
    attachments: [
      { name: "Coördinatiemodel installaties.ifc", type: "IFC" },
      { name: "Sparingenlijst week 29.xlsx", type: "XLSX" },
    ],
    issueIds: ["issue-clash"],
    modelPartIds: ["installations"],
  },
  {
    id: "afbouw",
    name: "Afbouw woningen en algemene ruimten",
    phase: "Afbouw",
    startDate: "2026-10-05",
    endDate: "2027-02-19",
    responsible: "Interbouw Afbouw",
    status: "Niet gestart",
    progress: 0,
    dependencies: ["binnenwanden", "installaties"],
    description: "Plafonds, tegelwerk, dekvloeren, schilderwerk, keukens en sanitair.",
    attachments: [{ name: "Afbouwplanning blok A.pdf", type: "PDF" }],
    issueIds: [],
    modelPartIds: ["finish"],
  },
  {
    id: "oplevering",
    name: "Testen, inregelen en opleveren",
    phase: "Afbouw",
    startDate: "2027-02-15",
    endDate: "2027-03-19",
    responsible: "Van Dijk Bouwgroep",
    status: "Niet gestart",
    progress: 0,
    dependencies: ["afbouw"],
    description: "Integrale test, vooropleveringen, restpunten, dossier en sleuteloverdracht.",
    attachments: [{ name: "Concept opleverprotocol.pdf", type: "PDF" }],
    issueIds: [],
    modelPartIds: [],
  },
];

export const buildingParts: BuildingPart[] = [
  { id: "terrain", name: "Bouwterrein", phase: "Terrein", activityId: "grondwerk", startDate: "2026-02-02", endDate: "2026-02-20", progress: 100, position: [0, -0.45, 0], scale: [12, 0.25, 9] },
  { id: "foundation-a", name: "Fundering blok A", phase: "Fundering", activityId: "fundering", startDate: "2026-02-16", endDate: "2026-03-20", progress: 100, position: [-2.7, -0.12, 0], scale: [4.8, 0.4, 5.8] },
  { id: "foundation-b", name: "Fundering blok B", phase: "Fundering", activityId: "fundering", startDate: "2026-02-16", endDate: "2026-03-20", progress: 100, position: [2.7, -0.12, 0], scale: [4.8, 0.4, 5.8] },
  { id: "ground-floor", name: "Beganegrondvloer", phase: "Ruwbouw", activityId: "beganegrondvloer", startDate: "2026-03-16", endDate: "2026-04-10", progress: 100, position: [0, 0.2, 0], scale: [10.2, 0.35, 6.2] },
  { id: "frame-left", name: "Draagconstructie west", phase: "Ruwbouw", activityId: "staalconstructie", startDate: "2026-04-06", endDate: "2026-06-12", delayed: true, progress: 88, position: [-2.6, 2.3, 0], scale: [4.8, 4.0, 5.8] },
  { id: "frame-right", name: "Draagconstructie oost", phase: "Ruwbouw", activityId: "staalconstructie", startDate: "2026-04-20", endDate: "2026-06-12", delayed: true, progress: 84, position: [2.6, 2.3, 0], scale: [4.8, 4.0, 5.8] },
  { id: "floor-1", name: "Verdiepingsvloer 1", phase: "Ruwbouw", activityId: "staalconstructie", startDate: "2026-04-27", endDate: "2026-05-15", delayed: true, progress: 100, position: [0, 1.85, 0], scale: [10, 0.25, 6] },
  { id: "floor-2", name: "Verdiepingsvloer 2", phase: "Ruwbouw", activityId: "staalconstructie", startDate: "2026-05-18", endDate: "2026-06-12", delayed: true, progress: 76, position: [0, 3.8, 0], scale: [10, 0.25, 6] },
  { id: "facade-front", name: "Voorgevel", phase: "Gevel & dak", activityId: "gevelsluiting", startDate: "2026-06-01", endDate: "2026-09-11", progress: 42, position: [0, 2.35, 3.05], scale: [10.2, 4.5, 0.18] },
  { id: "facade-back", name: "Achtergevel", phase: "Gevel & dak", activityId: "gevelsluiting", startDate: "2026-06-15", endDate: "2026-09-11", progress: 31, position: [0, 2.35, -3.05], scale: [10.2, 4.5, 0.18] },
  { id: "facade-left", name: "Kopgevel west", phase: "Gevel & dak", activityId: "gevelsluiting", startDate: "2026-06-08", endDate: "2026-08-14", progress: 58, position: [-5.05, 2.35, 0], scale: [0.18, 4.5, 6.0] },
  { id: "facade-right", name: "Kopgevel oost", phase: "Gevel & dak", activityId: "gevelsluiting", startDate: "2026-06-22", endDate: "2026-09-04", progress: 25, position: [5.05, 2.35, 0], scale: [0.18, 4.5, 6.0] },
  { id: "roof", name: "Dak", phase: "Gevel & dak", activityId: "dakwerk", startDate: "2026-07-06", endDate: "2026-08-28", progress: 35, position: [0, 4.75, 0], scale: [10.4, 0.35, 6.3] },
  { id: "walls-inner", name: "Binnenwanden", phase: "Afbouw", activityId: "binnenwanden", startDate: "2026-08-03", endDate: "2026-11-20", progress: 0, position: [0, 2.4, 0], scale: [7.5, 3.8, 4.3] },
  { id: "installations", name: "Installaties", phase: "Installaties", activityId: "installaties", startDate: "2026-07-20", endDate: "2026-12-18", progress: 12, position: [0, 3.2, 0], scale: [8.4, 0.35, 4.8] },
  { id: "finish", name: "Afbouw", phase: "Afbouw", activityId: "afbouw", startDate: "2026-10-05", endDate: "2027-02-19", progress: 0, position: [0, 2.4, 0], scale: [9.3, 3.8, 5.3] },
];

export const issues: Issue[] = [
  {
    id: "issue-steel",
    title: "Staalconstructie loopt drie dagen achter",
    description: "Twee hoofdliggers zijn later vrijgegeven door de constructeur. Montagevolgorde is aangepast.",
    priority: "Hoog",
    owner: "Jeroen van Loon",
    deadline: "2026-08-04",
    activityId: "staalconstructie",
    status: "In behandeling",
    comments: 5,
  },
  {
    id: "issue-windows",
    title: "Levering kozijnen nog niet bevestigd",
    description: "Definitieve leverweek voor kozijnen blok B ontbreekt. Impact op wind- en waterdicht-mijlpaal.",
    priority: "Kritiek",
    owner: "Sanne de Wit",
    deadline: "2026-08-05",
    activityId: "gevelsluiting",
    status: "Open",
    comments: 3,
  },
  {
    id: "issue-clash",
    title: "Installatiewerk conflicteert met plafondmontage",
    description: "Ventilatiekanaal in corridor 2.14 kruist de geplande draagprofielen van het plafond.",
    priority: "Hoog",
    owner: "Bram Smit",
    deadline: "2026-08-07",
    activityId: "installaties",
    status: "Open",
    comments: 7,
  },
  {
    id: "issue-drawing",
    title: "Revisietekening binnenwanden ontbreekt",
    description: "Laatste wijziging van de woningplattegronden is nog niet verwerkt in de uitvoeringstekening.",
    priority: "Middel",
    owner: "Nora El Amrani",
    deadline: "2026-08-10",
    activityId: "binnenwanden",
    status: "Open",
    comments: 2,
  },
  {
    id: "issue-resolved",
    title: "Sparing liftput gecontroleerd",
    description: "Maatvoering is afgestemd met liftleverancier en constructeur.",
    priority: "Laag",
    owner: "Jeroen van Loon",
    deadline: "2026-07-24",
    activityId: "fundering",
    status: "Opgelost",
    comments: 2,
  },
];

export const team: TeamMember[] = [
  { id: "tm1", name: "Jeroen van Loon", function: "Projectleider", company: "Van Dijk Bouwgroep", role: "Beheerder", lastActivity: "Vandaag, 15:42", rights: ["Alle projectdata", "Team beheren", "Rapportages"], initials: "JL" },
  { id: "tm2", name: "Sanne de Wit", function: "Werkvoorbereider", company: "Van Dijk Bouwgroep", role: "Werkvoorbereider", lastActivity: "Vandaag, 14:18", rights: ["Planning bewerken", "Documenten", "Aandachtspunten"], initials: "SW" },
  { id: "tm3", name: "Bram Smit", function: "Uitvoerder", company: "Van Dijk Bouwgroep", role: "Uitvoerder", lastActivity: "Vandaag, 12:03", rights: ["Voortgang", "Opmerkingen", "Aandachtspunten"], initials: "BS" },
  { id: "tm4", name: "Nora El Amrani", function: "BIM-coördinator", company: "ModelWerk Nederland", role: "Projectleider", lastActivity: "Gisteren, 16:52", rights: ["3D-model", "Documenten", "Planning"], initials: "NE" },
  { id: "tm5", name: "Koen de Graaf", function: "Montageleider", company: "Metaalbouw De Groot", role: "Onderaannemer", lastActivity: "Gisteren, 10:31", rights: ["Eigen activiteiten", "Opmerkingen", "Bijlagen"], initials: "KG" },
  { id: "tm6", name: "Marieke Bos", function: "Projectmanager", company: "Havenstede Ontwikkeling B.V.", role: "Opdrachtgever", lastActivity: "28 juli, 09:10", rights: ["Dashboard bekijken", "Rapportages", "Opmerkingen"], initials: "MB" },
  { id: "tm7", name: "Theo Janssen", function: "Directievoerder", company: "Bureau Bouwtoezicht", role: "Alleen-lezen", lastActivity: "25 juli, 11:08", rights: ["Alleen bekijken"], initials: "TJ" },
];

export const documents: ProjectDocument[] = [
  { id: "doc1", name: "Hoofdplanning Havenkwartier v12", category: "Planning", version: "12.0", updatedAt: "2026-07-31", owner: "Sanne de Wit", size: "2,4 MB" },
  { id: "doc2", name: "Coördinatiemodel bouwkundig", category: "Model", version: "C07", updatedAt: "2026-07-30", owner: "Nora El Amrani", size: "186 MB" },
  { id: "doc3", name: "Werkplan staalmontage", category: "Werkplan", activityId: "staalconstructie", version: "5.1", updatedAt: "2026-07-29", owner: "Koen de Graaf", size: "8,1 MB" },
  { id: "doc4", name: "Kozijnstaat blok A en B", category: "Inkoop", activityId: "gevelsluiting", version: "4.0", updatedAt: "2026-07-28", owner: "Sanne de Wit", size: "920 KB" },
  { id: "doc5", name: "Clashrapport installaties week 30", category: "BIM", activityId: "installaties", version: "30", updatedAt: "2026-07-27", owner: "Nora El Amrani", size: "14,7 MB" },
  { id: "doc6", name: "Verslag bouwvergadering 14", category: "Verslag", version: "1.0", updatedAt: "2026-07-25", owner: "Jeroen van Loon", size: "1,2 MB" },
];

export const projectStats = {
  activeProjects: 4,
  delayedActivities: 6,
  milestonesNext30Days: 8,
  teamMembers: 28,
};

export const phases = ["Terrein", "Fundering", "Ruwbouw", "Gevel & dak", "Installaties", "Afbouw"] as const;

export const projectForId = (id: string) => projects.find((project) => project.id === id) ?? projects[0];
export const activityForId = (id: string) => activities.find((activity) => activity.id === id);
